export const COMPACT_ABI = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "allocator", type: "address" },
      { internalType: "bytes", name: "proof", type: "bytes" },
    ],
    name: "__registerAllocator",
    outputs: [{ internalType: "uint96", name: "", type: "uint96" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes", name: "allocatorData", type: "bytes" },
          { internalType: "uint256", name: "nonce", type: "uint256" },
          { internalType: "uint256", name: "expires", type: "uint256" },
          { internalType: "uint256", name: "id", type: "uint256" },
          {
            components: [
              { internalType: "uint256", name: "claimant", type: "uint256" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            internalType: "struct Component[]",
            name: "recipients",
            type: "tuple[]",
          },
        ],
        internalType: "struct AllocatedTransfer",
        name: "transfer",
        type: "tuple",
      },
    ],
    name: "allocatedTransfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "address", name: "emissary", type: "address" },
    ],
    name: "assignEmissary",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
    ],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes", name: "allocatorData", type: "bytes" },
          { internalType: "bytes", name: "sponsorSignature", type: "bytes" },
          { internalType: "address", name: "sponsor", type: "address" },
          { internalType: "uint256", name: "nonce", type: "uint256" },
          { internalType: "uint256", name: "expires", type: "uint256" },
          { internalType: "bytes32", name: "witness", type: "bytes32" },
          { internalType: "string", name: "witnessTypestring", type: "string" },
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "uint256", name: "allocatedAmount", type: "uint256" },
          {
            components: [
              { internalType: "uint256", name: "claimant", type: "uint256" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            internalType: "struct Component[]",
            name: "claimants",
            type: "tuple[]",
          },
        ],
        internalType: "struct Claim",
        name: "claimPayload",
        type: "tuple",
      },
    ],
    name: "claim",
    outputs: [{ internalType: "bytes32", name: "claimHash", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "recipient", type: "address" },
    ],
    name: "depositERC20",
    outputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bytes32", name: "claimHash", type: "bytes32" },
      { internalType: "bytes32", name: "typehash", type: "bytes32" },
    ],
    name: "depositERC20AndRegister",
    outputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "arbiter", type: "address" },
      { internalType: "uint256", name: "nonce", type: "uint256" },
      { internalType: "uint256", name: "expires", type: "uint256" },
      { internalType: "bytes32", name: "typehash", type: "bytes32" },
      { internalType: "bytes32", name: "witness", type: "bytes32" },
    ],
    name: "depositERC20AndRegisterFor",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "bytes32", name: "claimHash", type: "bytes32" },
      { internalType: "uint256", name: "registeredAmount", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "address", name: "recipient", type: "address" },
    ],
    name: "depositNative",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "bytes32", name: "claimHash", type: "bytes32" },
      { internalType: "bytes32", name: "typehash", type: "bytes32" },
    ],
    name: "depositNativeAndRegister",
    outputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
      { internalType: "address", name: "arbiter", type: "address" },
      { internalType: "uint256", name: "nonce", type: "uint256" },
      { internalType: "uint256", name: "expires", type: "uint256" },
      { internalType: "bytes32", name: "typehash", type: "bytes32" },
      { internalType: "bytes32", name: "witness", type: "bytes32" },
    ],
    name: "depositNativeAndRegisterFor",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "bytes32", name: "claimHash", type: "bytes32" },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "disableForcedWithdrawal",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "enableForcedWithdrawal",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes", name: "allocatorData", type: "bytes" },
          { internalType: "bytes", name: "sponsorSignature", type: "bytes" },
          { internalType: "address", name: "sponsor", type: "address" },
          { internalType: "uint256", name: "nonce", type: "uint256" },
          { internalType: "uint256", name: "expires", type: "uint256" },
          { internalType: "bytes32", name: "witness", type: "bytes32" },
          { internalType: "string", name: "witnessTypestring", type: "string" },
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "uint256", name: "allocatedAmount", type: "uint256" },
          {
            components: [
              { internalType: "uint256", name: "claimant", type: "uint256" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            internalType: "struct Component[]",
            name: "claimants",
            type: "tuple[]",
          },
          {
            internalType: "bytes32[]",
            name: "additionalChains",
            type: "bytes32[]",
          },
          { internalType: "uint256", name: "chainIndex", type: "uint256" },
          {
            internalType: "uint256",
            name: "notarizedChainId",
            type: "uint256",
          },
        ],
        internalType: "struct ExogenousMultichainClaim",
        name: "claimPayload",
        type: "tuple",
      },
    ],
    name: "exogenousClaim",
    outputs: [{ internalType: "bytes32", name: "claimHash", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
    name: "extsload",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32[]", name: "slots", type: "bytes32[]" }],
    name: "extsload",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
    name: "exttload",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "forcedWithdrawal",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sponsor", type: "address" },
      { internalType: "bytes12", name: "lockTag", type: "bytes12" },
    ],
    name: "getEmissaryStatus",
    outputs: [
      { internalType: "enum EmissaryStatus", name: "status", type: "uint8" },
      {
        internalType: "uint256",
        name: "emissaryAssignmentAvailableAt",
        type: "uint256",
      },
      { internalType: "address", name: "currentEmissary", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
    ],
    name: "getForcedWithdrawalStatus",
    outputs: [
      { internalType: "enum ForcedWithdrawalStatus", name: "", type: "uint8" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "getLockDetails",
    outputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "enum ResetPeriod", name: "", type: "uint8" },
      { internalType: "enum Scope", name: "", type: "uint8" },
      { internalType: "bytes12", name: "", type: "bytes12" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sponsor", type: "address" },
      { internalType: "bytes32", name: "claimHash", type: "bytes32" },
      { internalType: "bytes32", name: "typehash", type: "bytes32" },
    ],
    name: "isRegistered",
    outputs: [{ internalType: "bool", name: "isActive", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "claimHash", type: "bytes32" },
      { internalType: "bytes32", name: "typehash", type: "bytes32" },
    ],
    name: "register",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes12", name: "lockTag", type: "bytes12" }],
    name: "scheduleEmissaryAssignment",
    outputs: [
      {
        internalType: "uint256",
        name: "emissaryAssignmentAvailableAt",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setOperator",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
];

export const ERC20_ABI = [
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [{ name: "", type: "string" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_spender", type: "address" },
      { name: "_value", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "success", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "_value", type: "uint256" }],
    name: "burn",
    outputs: [{ name: "success", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_from", type: "address" },
      { name: "_value", type: "uint256" },
    ],
    name: "burnFrom",
    outputs: [{ name: "success", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", type: "string" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_to", type: "address" },
      { name: "_value", type: "uint256" },
    ],
    name: "transfer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { name: "_spender", type: "address" },
      { name: "_value", type: "uint256" },
      { name: "_extraData", type: "bytes" },
    ],
    name: "approveAndCall",
    outputs: [{ name: "success", type: "bool" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;
